import { Products } from "./types/type";

export const data: Products[] = [
    {
      id: "1",
      name: 'Laptop',
      productType: 'Electronics',
      imageUrl:"https://cdn.britannica.com/77/170477-050-1C747EE3/Laptop-computer.jpg",
      categories: 'Gadgets',
      manufacturer: 'Manufacturer 1',
      countryOfOrigin: 'USA',
      price: "40000",
    },
    {
      id: "2",
      name: 'Computer',
      productType: 'Electronics',
      imageUrl:"https://m.media-amazon.com/images/I/71snht4ZY+L._AC_UF1000,1000_QL80_.jpg",
      categories: 'Gadgets',
      manufacturer: 'Manufacturer 2',
      countryOfOrigin: 'China',
      price: "45000",
    },
    {
      id: "3",
      name: 'Mobile',
      productType: 'Electronics',
      imageUrl:"https://economictimes.indiatimes.com/thumb/msid-98897778,width-1200,height-1200,resizemode-4,imgsize-35708/6-latest-mobile-phones-with-12gb-ram-in-india.jpg?from=mdr",
      categories: 'Smartphone',
      manufacturer: 'Manufacturer 3',
      countryOfOrigin: 'Korea',
      price: "15000",
    },
    {
      id: "4",
      name: 'Pressure Cooker',
      productType: 'Utensis',
      imageUrl:"https://rukminim2.flixcart.com/image/612/612/xif0q/pressure-cooker/s/n/z/-original-imagtcm3mjrgwda3.jpeg?q=70",
      categories: 'Utensis',
      manufacturer: 'Manufacturer 4',
      countryOfOrigin: 'India',
      price: "5000",
    },
    {
      id: "5",
      name: 'Fan',
      productType: 'Electronics',
      imageUrl:"https://orpatgroup.com/wp-content/uploads/2022/12/brown-fan-1.jpg",
      categories: 'Gadgets',
      manufacturer: 'Manufacturer 1',
      countryOfOrigin: 'India',
      price: "1500",
    },
    {
      id: "6",
      name: 'Air Conditional',
      productType: 'AC',
      imageUrl:"https://os-wordpress-media.s3.ap-south-1.amazonaws.com/blog/wp-content/uploads/2020/11/24212247/Air-Conditioner-Buying-Guide-1140x570.jpg",
      categories: 'Gadgets',
      manufacturer: 'Abc',
      countryOfOrigin: 'India',
      price: "30000",
    }
  ];

